export const GET_PAYMENTS_REQUEST = 'GET_PAYMENTS_REQUEST';
export const GET_PAYMENTS_REQUEST_SUCCESS = 'GET_PAYMENTS_REQUEST_SUCCESS';
export const GET_PAYMENTS_REQUEST_FAILURE = 'GET_PAYMENTS_REQUEST_FAILURE';

export const GET_PAYMENTS_FOR_LEADER_REQUEST = 'GET_PAYMENTS_FOR_LEADER_REQUEST';
export const GET_PAYMENTS_FOR_LEADER_SUCCESS = 'GET_PAYMENTS_FOR_LEADER_SUCCESS';
export const GET_PAYMENTS_FOR_LEADER_FAILURE = 'GET_PAYMENTS_FOR_LEADER_FAILURE';

export const DECLINE_PAYMENT_REQUEST = 'DECLINE_PAYMENT_REQUEST';
export const DECLINE_PAYMENT_SUCCESS = 'DECLINE_PAYMENT_SUCCESS';
export const DECLINE_PAYMENT_FAILURE = 'DECLINE_PAYMENT_FAILURE';

export const SET_APPROVED_PAYMENT_ID = 'SET_APPROVED_PAYMENT_ID';
export const SET_DECLINED_PAYMENT_ID = 'SET_DECLINED_PAYMENT_ID';

export const APPROVE_PAYMENT_REQUEST = 'APPROVE_PAYMENT_REQUEST';
export const APPROVE_PAYMENT_SUCCESS = 'APPROVE_PAYMENT_SUCCESS';
export const APPROVE_PAYMENT_FAILURE = 'APPROVE_PAYMENT_FAILURE';

export const ADD_PENDING_PAYMENT = 'ADD_PENDING_PAYMENT';
export const ADD_PENDING_PAYMENT_SUCCESS = 'ADD_PENDING_PAYMENT_SUCCESS';
export const ADD_PENDING_PAYMENT_FAILURE = 'ADD_PENDING_PAYMENT_FAILURE';

export const GET_FILTERED_LEADERS = 'GET_FILTERED_LEADERS';
export const GET_FILTERED_LEADERS_SUCCESS = 'GET_FILTERED_LEADERS_SUCCESS';
export const GET_FILTERED_LEADERS_FAILURE = 'GET_FILTERED_LEADERS_FAILURE';

export const SET_CURRENT_PAYMENT = 'SET_CURRENT_PAYMENT';
export const SET_CURRENT_PAYMENT_SUCCESS = 'SET_CURRENT_PAYMENT_SUCCESS';

export const NUDGE_PAYMENT_REQUEST = 'NUDGE_PAYMENT_REQUEST';
export const NUDGE_PAYMENT_SUCCESS = 'NUDGE_PAYMENT_SUCCESS';
export const NUDGE_PAYMENT_FAILURE = 'NUDGE_PAYMENT_FAILURE';

export const DONE_PAYMENT_REQUEST = 'DONE_PAYMENT_REQUEST';
export const DONE_PAYMENT_SUCCESS = 'DONE_PAYMENT_SUCCESS';
export const DONE_PAYMENT_FAILURE = 'DONE_PAYMENT_FAILURE';

