export const PAYMENT_ACCOUNT_SET_DATA = 'PAYMENT_ACCOUNT_SET_DATA';
export const PAYMENT_ACCOUNT_REMOVE_SET_DATA = 'PAYMENT_ACCOUNT_REMOVE_SET_DATA';

export const GET_PAYMENT_ACCOUNTS_REQUEST = 'GET_PAYMENT_ACCOUNTS_REQUEST;';
export const GET_PAYMENT_ACCOUNTS_REQUEST_SUCCESS = 'GET_PAYMENT_ACCOUNTS_REQUEST_SUCCESS';
export const GET_PAYMENT_ACCOUNTS_REQUEST_FAILURE = 'GET_PAYMENT_ACCOUNTS_REQUEST_FAILURE';

export const GET_FILTERED_PAYMENT_ACCOUNTS = 'GET_FILTERED_PAYMENT_ACCOUNTS';
export const GET_FILTERED_PAYMENT_ACCOUNTS_SUCCESS = 'GET_FILTERED_PAYMENT_ACCOUNTS_SUCCESS';
export const GET_FILTERED_PAYMENT_ACCOUNTS_FAILURE = 'GET_FILTERED_PAYMENT_ACCOUNTS_SUCCESS';
