export const USER_SET_DATA = 'USER_SET_DATA';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE';

export const UPDATE_USER_COMPANY_DATA_REQUEST = 'UPDATE_USER_COMPANY_DATA_REQUEST';
export const UPDATE_USER_COMPANY_DATA_SUCCESS = 'UPDATE_USER_COMPANY_DATA_SUCCESS';
export const UPDATE_USER_COMPANY_DATA_FAILURE = 'UPDATE_USER_COMPANY_DATA_FAILURE';

export const SET_SIGN_UP_DATA_STEP_1 = 'SET_SIGN_UP_DATA_STEP_1';
export const SET_SIGN_UP_DATA_STEP_1_SUCCESS = 'SET_SIGN_UP_DATA_STEP_1_SUCCESS';
export const SET_SIGN_UP_DATA_STEP_1_FAILURE = 'SET_SIGN_UP_DATA_STEP_1_FAILURE';

export const SET_SIGN_UP_DATA_STEP_2 = 'SET_SIGN_UP_DATA_STEP_2';
export const SET_SIGN_UP_DATA_STEP_2_SUCCESS = 'SET_SIGN_UP_DATA_STEP_2_SUCCESS';
export const SET_SIGN_UP_DATA_STEP_2_FAILURE = 'SET_SIGN_UP_DATA_STEP_2_FAILURE';

export const SET_SIGN_UP_DATA_STEP_3 = 'SET_SIGN_UP_DATA_STEP_3';
export const SET_SIGN_UP_DATA_STEP_3_SUCCESS = 'SET_SIGN_UP_DATA_STEP_3_SUCCESS';
export const SET_SIGN_UP_DATA_STEP_3_FAILURE = 'SET_SIGN_UP_DATA_STEP_3_FAILURE';

export const CLEAR_SIGN_UP_DATA = 'CLEAR_SIGN_UP_DATA';
export const CLEAR_EXTRA_ERROR = 'CLEAR_EXTRA_ERROR';

export const SIGN_UP_CONFIRMED = 'SIGN_UP_CONFIRMED';
export const SIGN_UP_CONFIRMED_SUCCESS = 'SIGN_UP_CONFIRMED_SUCCESS';
export const SIGN_UP_CONFIRMED_FAILURE = 'SIGN_UP_CONFIRMED_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
