name: deploy-api

on:
  push:
    branches:
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Cheking out the code
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Set a stage
        run: echo "::set-env name=STAGE::${GITHUB_REF#refs/heads/}"

      - name: Prepare GitHub secrets names
        run: |
          echo "::set-env name=AWS_ACCESS_KEY_ID_SECRET_NAME::${STAGE}_AWS_ACCESS_KEY_ID"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY_SECRET_NAME::${STAGE}_AWS_SECRET_ACCESS_KEY"

      - name: Set environment variables based on GitHub secrets names
        run: |
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets[env.AWS_ACCESS_KEY_ID_SECRET_NAME] }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets[env.AWS_SECRET_ACCESS_KEY_SECRET_NAME] }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build the React app
        run: REACT_APP_STAGE=$STAGE npm run build
        env:
          GENERATE_SOURCEMAP: false

      - name: Deploy the React app to the S3 bucket
        run: |
          aws s3 sync --delete ./build/ s3://$STAGE-app.certifier.me